<template>
    <div class="row back-row">
        <h2>Select type of password</h2>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-6">
                <a href="/password-generated">
                    <CardCmp :cardTitle=card1.title :cardDescription=card1.description />
                </a>
            </div>
            <div class="col-6">
                <a href="#">
                    <CardCmp :cardTitle=card2.title :cardDescription=card2.description />
                </a>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-6">
                <a href="#">
                    <CardCmp :cardTitle=card3.title :cardDescription=card3.description />
                </a>
            </div>
            <div class="col-6">
                <a href="#">
                    <CardCmp :cardTitle=card4.title :cardDescription=card4.description />
                </a>
            </div>
        </div>
    </div>
</template>
<script>
import CardCmp from '../CardCmp.vue'

export default {
    data() {
        return {
            card1: {
                title: "Basic password",
                description: "Random password"
            },
            card2: {
                title: "Choose Length",
                description: "Password generated by wish length"
            },
            card3: {
                title: "Customize password",
                description: "Custom password requirements"
            },
            card4: {
                title: "Exact password",
                description: "The password exactly how do you want"
            }
        }
    },
    components: {
        CardCmp
    }
}
</script>
<style>
</style>