<template>
    <div class="row back-row">
        <h2>Select type of password</h2>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-6">
                <router-link :to="{ name: 'PasswordGenerated'}">
                    <CardCmp :cardTitle=card1.title :cardDescription=card1.description />
                </router-link>
            </div>
            <div class="col-6">
                <router-link :to="{ name: 'PasswordForm', state: { title: card2.titleChild, subTitle: card2.subTitleChild, flag: card2.flag } }">
                    <CardCmp :cardTitle=card2.title :cardDescription=card2.description />
                </router-link>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-6">
                <router-link :to="{ name: 'PasswordForm', state: { title: card3.titleChild, subTitle: card3.subTitleChild, flag: card3.flag } }">
                    <CardCmp :cardTitle=card3.title :cardDescription=card3.description />
                </router-link>
            </div>
            <div class="col-6">
                <router-link :to="{ name: 'PasswordForm', state: { title: card4.titleChild, subTitle: card4.subTitleChild, flag: card4.flag } }">
                    <CardCmp :cardTitle=card4.title :cardDescription=card4.description />
                </router-link>
            </div>
        </div>
    </div>
</template>
<script>
import CardCmp from '../CardCmp.vue'

export default {
    data() {
        return {
            card1: {
                title: "Basic password",
                description: "Random password",
            },
            card2: {
                title: "Choose Length",
                description: "Password generated by wish length",
                titleChild: "Length password",
                subTitleChild: "Length of you password",
                flag: "length"
            },
            card3: {
                title: "Customize password",
                description: "Custom password requirements",
                titleChild: "Customize password",
                subTitleChild: "Characteristic of password",
                flag: "custom"
            },
            card4: {
                title: "Exact password",
                description: "The password exactly how do you want",
                titleChild: "Exact password",
                subTitleChild: "Password elements",
                flag: "exact"
            }
        }
    },
    components: {
        CardCmp
    }
}
</script>
<style>
br{
    display: block;
    margin: 20px 0;
    content: " ";
}
</style>